name: Deploy Azure Logic App

on:
  workflow_call:
    inputs:
      resource-group:
        required: true
        type: string
      logic-app-name:
        required: true
        type: string
      location:
        required: true
        type: string
      storage-account-name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Azure Credentials
      run: |
        echo "AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}"
        echo "CLIENT_ID: $(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -r .clientId)"
        echo "TENANT_ID: $(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -r .tenantId)"
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Logic App
      run: |
        RESOURCE_GROUP=${{ inputs.resource-group }}
        LOGIC_APP_NAME=${{ inputs.logic-app-name }}
        LOCATION=${{ inputs.location }}
        STORAGE_ACCOUNT=${{ inputs['storage-account-name'] }}

        # Create resource group if it doesn't exist
        az group create --name $RESOURCE_GROUP --location $LOCATION

        # Deploy Logic App
        az logicapp standard create --resource-group $RESOURCE_GROUP --name $LOGIC_APP_NAME --storage-account $STORAGE_ACCOUNT --location $LOCATION --sku-name Standard

        # Deploy Logic App workflow
        az logicapp deployment create --resource-group $RESOURCE_GROUP --name $LOGIC_APP_NAME --content-path ./logic-app
