name: Deploy Azure Logic App

on:
  push:
    branches:
      - dafault

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Logic App
      run: |
        RESOURCE_GROUP=<your-resource-group>
        LOGIC_APP_NAME=<your-logic-app-name>
        LOCATION=<your-location>
        STORAGE_ACCOUNT=<your-storage-account-name>

        # Create resource group if it doesn't exist
        az group create --name $RESOURCE_GROUP --location $LOCATION

        # Deploy Logic App
        az logicapp standard create --resource-group $RESOURCE_GROUP --name $LOGIC_APP_NAME --storage-account $STORAGE_ACCOUNT --location $LOCATION --sku-name Standard

        # Deploy Logic App workflow
        az logicapp deployment create --resource-group $RESOURCE_GROUP --name $LOGIC_APP_NAME --content-path ./path-to-your-logic-app
