name: Deploy Azure Logic App

on:
  workflow_call:
    inputs:
      resource-group:
        required: true
        type: string
      logic-app-name:
        required: true
        type: string
      location:
        required: true
        type: string
      storage-account-name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Logic App
      run: |
        RESOURCE_GROUP=${{ inputs.resource-group }}
        LOGIC_APP_NAME=${{ inputs.logic-app-name }}
        LOCATION=${{ inputs.location }}
        STORAGE_ACCOUNT=${{ inputs['storage-account-name'] }}

        # Create resource group if it doesn't exist
        az group create --name $RESOURCE_GROUP --location $LOCATION

        # Deploy Logic App
        az logicapp create -g $RESOURCE_GROUP --subscription a8f3d4e3-c60d-48bf-a230-bb008ff8a887 -p ASP-edekatests-bf2f -n $LOGIC_APP_NAME -s $STORAGE_ACCOUNT

        dir
        cd ./logic-app
        zip -r ${{ github.run_id }}.zip *

        az webapp deploy --resource-group $RESOURCE_GROUP --name $LOGIC_APP_NAME --src-path ${{ github.run_id }}.zip --type=zip --clean false
